## Aquisição e exploração dos dados

- [x] Levantamento e Exploração de dados relacionados aos casos de Tuberculose no Brasil e no Ceará:
    - [x] Limpeza dos Dados brutos;
    - [x] Filtragem dos dados relevantes;
    - [x] Conversão de dados string para datetime;
    - [x] Exportar dados processados
- [ ] Levantamento e Exploração de dados relacionados à Vacinação de BCG no Brasil e no Ceará:
    - [ ] Limpeza dos Dados brutos;
    - [ ] Filtragem dos dados relevantes;
    - [ ] Conversão de dados string para datetime.
    - [ ] Exportar dados processados

### Descrição dos dados:

 - [Bases de dados - DATASUS/TABNET](http://www2.datasus.gov.br/DATASUS/index.php?area=02)
 
 - **casos_tuberculose_ano_uf.csv**: TUBERCULOSE - Casos confirmados notificados no Sistema de Informação de Agravos de Notificação - Brasil. Casos confirmados por UF de notificação e Ano Notificaçã0. Período 2001-2020. [Fonte: DATASUS/TABNET](http://www2.datasus.gov.br/DATASUS/index.php?area=02).
 - **doses_cv_ano_uf.csv**: Imunizações - Cobertura - Brasil. Doses Cáculos CV por Unidade da Federação e Ano. Período:1994-2019. [Fonte: DATASUS/TABNET](http://www2.datasus.gov.br/DATASUS/index.php?area=02).
 - **doses_cv_imuno_uf.csv**: Imunizações - Cobertura - Brasil. Doses Cáculos CV por Unidade da Federação e Imuno. Período:1994-2019. [Fonte: DATASUS/TABNET](http://www2.datasus.gov.br/DATASUS/index.php?area=02).
 - **doses_cv_imuno_uf-2009.csv**: Imunizações - Cobertura - Brasil. Doses Cáculos CV por Unidade da Federação e Imuno. Período:2009. [Fonte: DATASUS/TABNET](http://www2.datasus.gov.br/DATASUS/index.php?area=02).
 - **doses_cv_imuno_uf-2019.csv**: Imunizações - Cobertura - Brasil. Doses Cáculos CV por Unidade da Federação e Imuno. Período:2019. [Fonte: DATASUS/TABNET](http://www2.datasus.gov.br/DATASUS/index.php?area=02).

In [16]:
# Importa bibliotecas
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import datetime
from datetime import date

## CASOS TUBERCULOSE

In [2]:
# Importar dados
dados_tuberculose = pd.read_csv("../data/raw/casos_tuberculose_ano_uf.csv",
                                encoding = "ISO-8859-1",
                                skiprows = 3, sep = ";",
                                skipfooter = 19,
                                thousands = ".",
                                decimal = ",")
dados_tuberculose.head()

<ipython-input-2-1cc7c8c67f96>:2: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support skipfooter; you can avoid this warning by specifying engine='python'.
  dados_tuberculose = pd.read_csv("../data/raw/casos_tuberculose_ano_uf.csv",

,UF de notificação,1980,1981,1982,1983,1984,1985,1986,1987,1988,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,Total
0,11 Rondônia,-,-,-,-,-,-,-,-,-,...,720,690,660,779,773,693,735,608,16,13116
1,12 Acre,-,-,-,-,-,-,-,-,-,...,394,440,389,436,495,485,591,602,20,8164
2,13 Amazonas,-,-,-,-,-,-,-,-,-,...,3066,3127,3401,3284,3688,3777,3943,3537,46,58320
3,14 Roraima,-,-,-,-,-,-,-,-,-,...,167,148,170,162,212,268,323,324,14,3731
4,15 Pará,-,-,-,-,-,-,-,-,-,...,4131,3944,3974,4216,4524,4698,5496,4927,94,83153

In [3]:
# UF para Index

dados_tuberculose = dados_tuberculose.set_index("UF de notificação")

In [4]:
dados_tuberculose.select_dtypes("object")

,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1995,1996,1997,1998,1999
UF de notificação,,,,,,,,,,,,,,,,,,,
11 Rondônia,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-
12 Acre,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-
13 Amazonas,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-
14 Roraima,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-
15 Pará,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-
16 Amapá,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-
17 Tocantins,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-
21 Maranhão,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-
22 Piauí,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-
23 Ceará,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-
24 Rio Grande do Norte,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-
25 Paraíba,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-
26 Pernambuco,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-
27 Alagoas,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-
28 Sergipe,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-
29 Bahia,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-
31 Minas Gerais,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-
32 Espírito Santo,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-
33 Rio de Janeiro,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-
35 São Paulo,1,3,2,3,1,1,1,2,1,4,2,4,5,4,3,1,2,3,2
41 Paraná,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-
42 Santa Catarina,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-
43 Rio Grande do Sul,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-
50 Mato Grosso do Sul,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-
51 Mato Grosso,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-
52 Goiás,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-
53 Distrito Federal,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-

In [5]:
# Ocupar células com dados não nulos

dados_tuberculose = dados_tuberculose.replace("-", np.nan)
dados_tuberculose.head()

,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,Total
UF de notificação,,,,,,,,,,,,,,,,,,,,,
11 Rondônia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,720,690,660,779,773,693,735,608,16,13116
12 Acre,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,394,440,389,436,495,485,591,602,20,8164
13 Amazonas,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3066,3127,3401,3284,3688,3777,3943,3537,46,58320
14 Roraima,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,167,148,170,162,212,268,323,324,14,3731
15 Pará,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4131,3944,3974,4216,4524,4698,5496,4927,94,83153

In [6]:
# Checagem de dados:
dados_tuberculose.T.info()
#dados_tuberculose["1999"]

<class 'pandas.core.frame.DataFrame'>
Index: 41 entries, 1980 to Total
Data columns (total 27 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   11 Rondônia             22 non-null     object
 1   12 Acre                 22 non-null     object
 2   13 Amazonas             22 non-null     object
 3   14 Roraima              22 non-null     object
 4   15 Pará                 22 non-null     object
 5   16 Amapá                22 non-null     object
 6   17 Tocantins            22 non-null     object
 7   21 Maranhão             22 non-null     object
 8   22 Piauí                22 non-null     object
 9   23 Ceará                22 non-null     object
 10  24 Rio Grande do Norte  22 non-null     object
 11  25 Paraíba              22 non-null     object
 12  26 Pernambuco           22 non-null     object
 13  27 Alagoas              22 non-null     object
 14  28 Sergipe              22 non-null     object
 15  29 Bahia                22 non-null     object
 16  31 Minas Gerais         22 non-null     object
 17  32 Espírito Santo       22 non-null     object
 18  33 Rio de Janeiro       22 non-null     object
 19  35 São Paulo            41 non-null     object
 20  41 Paraná               22 non-null     object
 21  42 Santa Catarina       22 non-null     object
 22  43 Rio Grande do Sul    22 non-null     object
 23  50 Mato Grosso do Sul   22 non-null     object
 24  51 Mato Grosso          22 non-null     object
 25  52 Goiás                22 non-null     object
 26  53 Distrito Federal     22 non-null     object
dtypes: object(27)
memory usage: 10.0+ KB

In [7]:
dados_tuberculose.isnull().sum().sum()

494

In [8]:
# Converter dados de "object" para "float64"

dados_tuberculose = dados_tuberculose.astype("float64")
dados_tuberculose

,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,Total
UF de notificação,,,,,,,,,,,,,,,,,,,,,
11 Rondônia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,720.0,690.0,660.0,779.0,773.0,693.0,735.0,608.0,16.0,13116.0
12 Acre,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,394.0,440.0,389.0,436.0,495.0,485.0,591.0,602.0,20.0,8164.0
13 Amazonas,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3066.0,3127.0,3401.0,3284.0,3688.0,3777.0,3943.0,3537.0,46.0,58320.0
14 Roraima,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,167.0,148.0,170.0,162.0,212.0,268.0,323.0,324.0,14.0,3731.0
15 Pará,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4131.0,3944.0,3974.0,4216.0,4524.0,4698.0,5496.0,4927.0,94.0,83153.0
16 Amapá,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,220.0,210.0,223.0,284.0,294.0,268.0,355.0,319.0,7.0,5287.0
17 Tocantins,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,190.0,193.0,190.0,208.0,182.0,226.0,234.0,205.0,9.0,4612.0
21 Maranhão,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2316.0,2081.0,2277.0,2412.0,2502.0,2654.0,2705.0,2498.0,73.0,52125.0
22 Piauí,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,903.0,815.0,773.0,794.0,799.0,875.0,862.0,779.0,27.0,22137.0
23 Ceará,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4071.0,3884.0,4014.0,4034.0,4314.0,4560.0,4580.0,3864.0,110.0,85897.0
24 Rio Grande do Norte,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1273.0,1194.0,1142.0,1183.0,1329.0,1599.0,1453.0,1668.0,47.0,25518.0
25 Paraíba,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1452.0,1332.0,1234.0,1221.0,1346.0,1512.0,1477.0,1100.0,59.0,27001.0
26 Pernambuco,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5488.0,5460.0,5643.0,5529.0,5934.0,5922.0,6189.0,5539.0,153.0,106942.0
27 Alagoas,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1313.0,1271.0,1065.0,1227.0,1295.0,1326.0,1304.0,1074.0,52.0,26485.0
28 Sergipe,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,712.0,793.0,766.0,792.0,820.0,973.0,1012.0,903.0,32.0,14647.0
29 Bahia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5748.0,5667.0,5315.0,5272.0,5500.0,5659.0,5698.0,4670.0,142.0,130208.0
31 Minas Gerais,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4196.0,4220.0,4014.0,4068.0,4097.0,4228.0,4317.0,3998.0,104.0,92381.0
32 Espírito Santo,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1378.0,1315.0,1390.0,1236.0,1321.0,1480.0,1485.0,1791.0,62.0,29322.0
33 Rio de Janeiro,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,13487.0,13042.0,13295.0,13537.0,14086.0,14743.0,15044.0,13621.0,280.0,291671.0
35 São Paulo,1.0,3.0,2.0,3.0,1.0,1.0,1.0,2.0,1.0,4.0,...,19840.0,19654.0,20408.0,20405.0,22109.0,22454.0,22384.0,19486.0,260.0,390274.0
41 Paraná,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2635.0,2557.0,2484.0,2444.0,2388.0,2735.0,2664.0,2597.0,76.0,57039.0
42 Santa Catarina,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2278.0,2236.0,2142.0,2213.0,2256.0,2240.0,2310.0,1757.0,71.0,40758.0
43 Rio Grande do Sul,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,6342.0,6397.0,6398.0,6036.0,6524.0,6832.0,7502.0,6680.0,211.0,122153.0
50 Mato Grosso do Sul,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1097.0,995.0,1003.0,1132.0,1131.0,1447.0,1420.0,1361.0,38.0,21577.0
51 Mato Grosso,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1891.0,1829.0,1406.0,1512.0,1424.0,1405.0,1538.0,1306.0,33.0,27923.0
52 Goiás,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1076.0,993.0,1093.0,1031.0,1147.0,1219.0,1172.0,1101.0,36.0,21508.0
53 Distrito Federal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,467.0,531.0,472.0,462.0,407.0,474.0,484.0,430.0,12.0,10474.0

In [9]:
dados_tuberculose.T.info()

<class 'pandas.core.frame.DataFrame'>
Index: 41 entries, 1980 to Total
Data columns (total 27 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   11 Rondônia             22 non-null     float64
 1   12 Acre                 22 non-null     float64
 2   13 Amazonas             22 non-null     float64
 3   14 Roraima              22 non-null     float64
 4   15 Pará                 22 non-null     float64
 5   16 Amapá                22 non-null     float64
 6   17 Tocantins            22 non-null     float64
 7   21 Maranhão             22 non-null     float64
 8   22 Piauí                22 non-null     float64
 9   23 Ceará                22 non-null     float64
 10  24 Rio Grande do Norte  22 non-null     float64
 11  25 Paraíba              22 non-null     float64
 12  26 Pernambuco           22 non-null     float64
 13  27 Alagoas              22 non-null     float64
 14  28 Sergipe              22 non-null     float64
 15  29 Bahia                22 non-null     float64
 16  31 Minas Gerais         22 non-null     float64
 17  32 Espírito Santo       22 non-null     float64
 18  33 Rio de Janeiro       22 non-null     float64
 19  35 São Paulo            41 non-null     float64
 20  41 Paraná               22 non-null     float64
 21  42 Santa Catarina       22 non-null     float64
 22  43 Rio Grande do Sul    22 non-null     float64
 23  50 Mato Grosso do Sul   22 non-null     float64
 24  51 Mato Grosso          22 non-null     float64
 25  52 Goiás                22 non-null     float64
 26  53 Distrito Federal     22 non-null     float64
dtypes: float64(27)
memory usage: 10.0+ KB

In [10]:
dados_tuberculose.columns
dados_tuberculose = dados_tuberculose.drop("Total", axis = 1)
dados_tuberculose.head()

,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
UF de notificação,,,,,,,,,,,,,,,,,,,,,
11 Rondônia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,694.0,720.0,690.0,660.0,779.0,773.0,693.0,735.0,608.0,16.0
12 Acre,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,414.0,394.0,440.0,389.0,436.0,495.0,485.0,591.0,602.0,20.0
13 Amazonas,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2830.0,3066.0,3127.0,3401.0,3284.0,3688.0,3777.0,3943.0,3537.0,46.0
14 Roraima,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,141.0,167.0,148.0,170.0,162.0,212.0,268.0,323.0,324.0,14.0
15 Pará,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4040.0,4131.0,3944.0,3974.0,4216.0,4524.0,4698.0,5496.0,4927.0,94.0

In [11]:
# Seleção das Colunas a serem utilizadas

colunas_usaveis_tuberculose = dados_tuberculose.T.index[19:-1]
colunas_usaveis_tuberculose

Index(['2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009',
       '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018',
       '2019', '2020'],
      dtype='object')

In [12]:
usaveis_tuberculose = dados_tuberculose[colunas_usaveis_tuberculose]
usaveis_tuberculose.head()

,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
UF de notificação,,,,,,,,,,,,,,,,,,,,
11 Rondônia,662.0,636.0,648.0,623.0,628.0,518.0,544.0,563.0,665.0,575.0,686.0,694.0,720.0,690.0,660.0,779.0,773.0,693.0,735.0,608.0
12 Acre,353.0,373.0,370.0,350.0,329.0,383.0,315.0,327.0,364.0,342.0,392.0,414.0,394.0,440.0,389.0,436.0,495.0,485.0,591.0,602.0
13 Amazonas,2333.0,2271.0,2333.0,2557.0,2498.0,2442.0,2443.0,2691.0,2604.0,2750.0,2699.0,2830.0,3066.0,3127.0,3401.0,3284.0,3688.0,3777.0,3943.0,3537.0
14 Roraima,149.0,172.0,200.0,217.0,160.0,149.0,137.0,156.0,145.0,150.0,167.0,141.0,167.0,148.0,170.0,162.0,212.0,268.0,323.0,324.0
15 Pará,3447.0,3764.0,3936.0,4077.0,3992.0,3819.0,3741.0,3792.0,4091.0,4101.0,4349.0,4040.0,4131.0,3944.0,3974.0,4216.0,4524.0,4698.0,5496.0,4927.0

In [13]:
usaveis_por_ano = usaveis_tuberculose.T
usaveis_por_ano.head()

UF de notificação,11 Rondônia,12 Acre,13 Amazonas,14 Roraima,15 Pará,16 Amapá,17 Tocantins,21 Maranhão,22 Piauí,23 Ceará,...,32 Espírito Santo,33 Rio de Janeiro,35 São Paulo,41 Paraná,42 Santa Catarina,43 Rio Grande do Sul,50 Mato Grosso do Sul,51 Mato Grosso,52 Goiás,53 Distrito Federal
2001,662.0,353.0,2333.0,149.0,3447.0,216.0,280.0,2818.0,1547.0,3747.0,...,1614.0,16528.0,18649.0,3158.0,1595.0,5044.0,957.0,1359.0,1111.0,612.0
2002,636.0,373.0,2271.0,172.0,3764.0,295.0,330.0,2981.0,1471.0,4068.0,...,1596.0,16779.0,19867.0,3320.0,1851.0,5487.0,897.0,1259.0,1126.0,593.0
2003,648.0,370.0,2333.0,200.0,3936.0,274.0,275.0,2987.0,1400.0,5228.0,...,1533.0,15876.0,19204.0,3450.0,1868.0,5752.0,973.0,1230.0,1235.0,613.0
2004,623.0,350.0,2557.0,217.0,4077.0,277.0,280.0,2949.0,1576.0,4363.0,...,1528.0,15932.0,18612.0,3309.0,1855.0,5928.0,1047.0,1172.0,1093.0,626.0
2005,628.0,329.0,2498.0,160.0,3992.0,269.0,263.0,3179.0,1564.0,4695.0,...,1462.0,15268.0,17746.0,3373.0,1835.0,5644.0,1085.0,1350.0,1104.0,619.0

In [17]:
date.today()

datetime.date(2021, 7, 9)

In [18]:
usaveis_por_ano.index

Index(['2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009',
       '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018',
       '2019', '2020'],
      dtype='object')

In [32]:
def para_ano(ano_mes: str):
    ano: int = int(ano_mes)
    mes: str = 12
    return date(ano, mes, 1)

usaveis_por_ano.index = usaveis_por_ano.index.map(para_ano)
usaveis_por_ano.head()

UF de notificação,11 Rondônia,12 Acre,13 Amazonas,14 Roraima,15 Pará,16 Amapá,17 Tocantins,21 Maranhão,22 Piauí,23 Ceará,...,32 Espírito Santo,33 Rio de Janeiro,35 São Paulo,41 Paraná,42 Santa Catarina,43 Rio Grande do Sul,50 Mato Grosso do Sul,51 Mato Grosso,52 Goiás,53 Distrito Federal
2001-12-01,662.0,353.0,2333.0,149.0,3447.0,216.0,280.0,2818.0,1547.0,3747.0,...,1614.0,16528.0,18649.0,3158.0,1595.0,5044.0,957.0,1359.0,1111.0,612.0
2002-12-01,636.0,373.0,2271.0,172.0,3764.0,295.0,330.0,2981.0,1471.0,4068.0,...,1596.0,16779.0,19867.0,3320.0,1851.0,5487.0,897.0,1259.0,1126.0,593.0
2003-12-01,648.0,370.0,2333.0,200.0,3936.0,274.0,275.0,2987.0,1400.0,5228.0,...,1533.0,15876.0,19204.0,3450.0,1868.0,5752.0,973.0,1230.0,1235.0,613.0
2004-12-01,623.0,350.0,2557.0,217.0,4077.0,277.0,280.0,2949.0,1576.0,4363.0,...,1528.0,15932.0,18612.0,3309.0,1855.0,5928.0,1047.0,1172.0,1093.0,626.0
2005-12-01,628.0,329.0,2498.0,160.0,3992.0,269.0,263.0,3179.0,1564.0,4695.0,...,1462.0,15268.0,17746.0,3373.0,1835.0,5644.0,1085.0,1350.0,1104.0,619.0

In [34]:
usaveis_por_ano.index[0]

datetime.date(2001, 12, 1)

In [44]:
usaveis_tuberculose = usaveis_por_ano.T
usaveis_tuberculose.head()

,2001-12-01,2002-12-01,2003-12-01,2004-12-01,2005-12-01,2006-12-01,2007-12-01,2008-12-01,2009-12-01,2010-12-01,2011-12-01,2012-12-01,2013-12-01,2014-12-01,2015-12-01,2016-12-01,2017-12-01,2018-12-01,2019-12-01,2020-12-01
UF de notificação,,,,,,,,,,,,,,,,,,,,
11 Rondônia,662.0,636.0,648.0,623.0,628.0,518.0,544.0,563.0,665.0,575.0,686.0,694.0,720.0,690.0,660.0,779.0,773.0,693.0,735.0,608.0
12 Acre,353.0,373.0,370.0,350.0,329.0,383.0,315.0,327.0,364.0,342.0,392.0,414.0,394.0,440.0,389.0,436.0,495.0,485.0,591.0,602.0
13 Amazonas,2333.0,2271.0,2333.0,2557.0,2498.0,2442.0,2443.0,2691.0,2604.0,2750.0,2699.0,2830.0,3066.0,3127.0,3401.0,3284.0,3688.0,3777.0,3943.0,3537.0
14 Roraima,149.0,172.0,200.0,217.0,160.0,149.0,137.0,156.0,145.0,150.0,167.0,141.0,167.0,148.0,170.0,162.0,212.0,268.0,323.0,324.0
15 Pará,3447.0,3764.0,3936.0,4077.0,3992.0,3819.0,3741.0,3792.0,4091.0,4101.0,4349.0,4040.0,4131.0,3944.0,3974.0,4216.0,4524.0,4698.0,5496.0,4927.0

### Exportar dados

- Checar Documentação pandas: [Export DataFrame do csv Pandas](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_csv.html)

In [45]:
# Export dados usaveis como arquivo CSV

usaveis_tuberculose.to_csv("../data/processed/dados_tuberculose_uf_2001-2020.csv", index = False)